HEAD:
  mixed-port: 7890
  allow-lan: true
  mode: rule
  log-level: info
  external-controller: :9090
  dns:
    enable: true
    listen: 0.0.0.0:1053
    default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
    nameserver-policy:
      geosite:gfw,geolocation-!cn:
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query
      - https://8.8.8.8/dns-query
    nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://8.8.8.8/dns-query
    fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://8.8.8.8/dns-query
    fallback-filter:
      geoip: false
      geoip-code: CN
      ipcidr:
      - 240.0.0.0/4
    fake-ip-filter:
    - +.lan
    - +.microsoft*.com
    - localhost.ptlogin2.qq.com
TEST_URL: https://captive.apple.com
RULESET:
- - ğŸ¤– ChatBot
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/OpenAi.list
- - ğŸ¤– ChatBot
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/ChatBot.list
- - ğŸ¯ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/LocalAreaNetwork.list
- - ğŸ¯ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/UnBan.list
- - ğŸ›‘ ADblock
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanAD.list
- - ğŸƒ åº”ç”¨å‡€åŒ–
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanProgramAD.list
- - ğŸ›‘ ADblock
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanEasyList.list
- - ğŸ›‘ ADblock
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanEasyListChina.list
- - ğŸ›¡ï¸ éšç§é˜²æŠ¤
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanEasyPrivacy.list
- - ğŸ“¢ GoogleFCM
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/GoogleFCM.list
- - ğŸ“¢ GoogleæœåŠ¡
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Google.list
- - ğŸ¯ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Adobe.list
- - â“‚ï¸ MicrosoftBing
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Bing.list
- - â“‚ï¸ Microsoftäº‘ç›˜
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/OneDrive.list
- - â“‚ï¸ MicrosoftæœåŠ¡
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Microsoft.list
- - ğŸ Apple
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Apple.list
- - ğŸ“² Telegram
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Telegram.list
- - ğŸ“– Facebook
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Facebook.list
- - ğŸ“± Twitter
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Twitter.list
- -  ğŸ“¹ Instagram
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Instagram.list
- - ğŸ¶ ç½‘æ˜“éŸ³ä¹
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/NetEaseMusic.list
- - ğŸ¶ Spotify
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Spotify.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Epic.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Origin.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Sony.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Steam.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Nintendo.list
- - ğŸ“¹ Youtube
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/YouTube.list
- - ğŸ¥ Netflix
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Netflix.list
- - ğŸ“º Bahamut
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Bahamut.list
- - ğŸ“º Bilibili
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/BilibiliHMT.list
- - ğŸ“º Bilibili
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Bilibili.list
- - ğŸŒ å›½å†…åª’ä½“
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ChinaMedia.list
- - ğŸŒ Streaming
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ProxyMedia.list
- - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ProxyGFWlist.list
- - ğŸ¯ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ChinaIp.list
- - ğŸ¯ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ChinaDomain.list
- - ğŸ¯ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ChinaCompanyIp.list
- - ğŸ¯ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Download.list
- - ğŸ¯ China
  - '[]GEOIP,CN'
- - ğŸŸ æ¼ç½‘ä¹‹é±¼
  - '[]FINAL'
CUSTOM_PROXY_GROUP:
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  rule: false
- name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
  type: select
  manual: true
  rule: false
- name: ğŸ”¯ æ•…éšœè½¬ç§»
  type: fallback
  rule: false
- name: ğŸ”® è´Ÿè½½å‡è¡¡
  type: load-balance
  rule: false
- name: ğŸ¤– ChatBot
  type: select
  prior: PROXY
- name: ğŸ“² Telegram
  type: select
  prior: PROXY
- name: ğŸ“¹ Youtube
  type: select
  prior: PROXY
- name: ğŸ“– Facebook
  type: select
  prior: PROXY
- name: ğŸ“± Twitter
  type: select
  prior: PROXY
- name: ğŸ“¹ Instegram
  type: select
  prior: PROXY
- name: ğŸ¥ Netflix
  type: select
  prior: PROXY
- name: ğŸ“º Bahamut
  type: select
  prior: PROXY
- name: ğŸ“º Bilibili
  type: select
  prior: DIRECT
- name: ğŸŒ Streaming
  type: select
  prior: PROXY
- name: ğŸŒ å›½å†…åª’ä½“
  type: select
  prior: DIRECT
- name: ğŸ“¢ GoogleFCM
  type: select
  prior: DIRECT
- name: ğŸ“¢ GoogleæœåŠ¡
  type: select
  prior: PROXY
- name: â“‚ï¸ MicrosoftBing
  type: select
  prior: PROXY
- name: â“‚ï¸ Microsoftäº‘ç›˜
  type: select
  prior: DIRECT
- name: â“‚ï¸ MicrosoftæœåŠ¡
  type: select
  prior: DIRECT
- name: ğŸ Apple
  type: select
  prior: DIRECT
- name: ğŸ® Game
  type: select
  prior: DIRECT
- name: ğŸ¶ ç½‘æ˜“éŸ³ä¹
  type: select
  prior: DIRECT
- name: ğŸ¶ Spotify
  type: select
  prior: DIRECT
- name: ğŸ¯ China
  type: select
  prior: DIRECT
- name: ğŸ›‘ ADblock
  type: select
  prior: REJECT
- name: ğŸƒ åº”ç”¨å‡€åŒ–
  type: select
  prior: REJECT
- name: ğŸ›¡ï¸ éšç§é˜²æŠ¤
  type: select
  prior: REJECT
- name: ğŸŸ æ¼ç½‘ä¹‹é±¼
  type: select
  prior: PROXY
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡­ğŸ‡°|HK|Hong|Kong|HGC|WTT|CMI|æ¸¯
- name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡¹ğŸ‡¼|TW|Taiwan|æ–°åŒ—|å½°åŒ–|CHT|å°|HINET
- name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡¸ğŸ‡¬|SG|Singapore|ç‹®åŸ|^æ–°[^èŠ‚åŒ—]|[^åˆ·æ›´]æ–°[^èŠ‚åŒ—]
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡¯ğŸ‡µ|JP|Japan|Tokyo|Osaka|Saitama|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|æ—¥
- name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡°ğŸ‡·|KO?R|Korea|é¦–å°”|éŸ©|éŸ“
- name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
  type: url-test
  rule: false
  regex: ğŸ‡ºğŸ‡¸|US|America|United.*?States|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥
