HEAD:
  mixed-port: 7890
  allow-lan: true
  mode: rule
  log-level: info
  external-controller: :9090
  dns:
    enable: true
    listen: 0.0.0.0:1053
    default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
    - 1.1.1.1
    nameserver-policy:
      geosite:gfw,geolocation-!cn:
      - https://1.1.1.1/dns-query
      - https://1.0.0.1/dns-query
      - https://8.8.8.8/dns-query
    nameserver:
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
    - https://8.8.8.8/dns-query
    fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://8.8.8.8/dns-query
    fallback-filter:
      geoip: false
      geoip-code: CN
      ipcidr:
      - 240.0.0.0/4
    fake-ip-filter:
    - +.lan
    - +.microsoft*.com
    - localhost.ptlogin2.qq.com
TEST_URL: https://captive.apple.com
RULESET:
- - ğŸ¤– ChatGPT
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/OpenAi.list
- - ğŸ¤– ChatGPT
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/ChatGPT.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/LocalAreaNetwork.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/UnBan.list
- - ğŸ›‘ AdBlock
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanAD.list
- - ğŸ›‘ AdBlock
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanProgramAD.list
- - ğŸ›‘ AdBlock
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanEasyList.list
- - ğŸ›‘ AdBlock
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanEasyListChina.list
- - ğŸ›‘ AdBlock
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/BanEasyPrivacy.list
- - ğŸ“¢ Google
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/GoogleFCM.list
- - ğŸ“¢ Google
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Google.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Adobe.list
- - â“‚ï¸ Microsoft
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Bing.list
- - â“‚ï¸ Microsoft
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/OneDrive.list
- - â“‚ï¸ Microsoft
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Microsoft.list
- - ğŸ Apple
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Apple.list
- - ğŸ“² Telegram
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Telegram.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/NetEaseMusic.list
- - ğŸ¶ Spotify
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Spotify.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Epic.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Origin.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Sony.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Steam.list
- - ğŸ® Game
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Nintendo.list
- - ğŸ“¹ Youtube
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/YouTube.list
- - ğŸ¥ Streaming
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Netflix.list
- - ğŸ“º Bahamut
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Bahamut.list
- - ğŸ“º Bilibili
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/BilibiliHMT.list
- - ğŸ“º Bilibili
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Ruleset/Bilibili.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ChinaMedia.list
- - ğŸ¥ Streaming
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ProxyMedia.list
- - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ProxyGFWlist.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ChinaIp.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ChinaDomain.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/ChinaCompanyIp.list
- - ğŸŒ China
  - https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/Download.list
- - ğŸŒ China
  - '[]GEOIP,CN'
- - ğŸŸ Final
  - '[]FINAL'
Custom_Proxies_Group:
- name: â™»ï¸ Auto
  type: urltest
  rule: false
- name: ğŸš€ Selector
  type: select
  manual: true
  rule: false
- name: ğŸ”¯ Fallback
  type: fallback
  rule: false
- name: ğŸ”® LoadBalance
  type: load-balance
  rule: false
- name: ğŸ”® HongKong-LoadBalance
  type: load-balance
  rule: false
  regex: ğŸ‡­ğŸ‡°|HK|Hong|Kong|HGC|WTT|CMI|æ¸¯
- name: ğŸ¤– ChatGPT
  type: select
  prior: Proxies
- name: ğŸ“¢ Google
  type: select
  prior: Proxies
- name: ğŸ“² Telegram
  type: select
  prior: Proxies
- name: ğŸ“¹ Youtube
  type: select
  prior: Proxies
- name: ğŸ¥ Streaming
  type: select
  prior: Proxies
- name: ğŸ“º Bahamut
  type: select
  prior: Proxies
- name: ğŸ¶ Spotify
  type: select
  prior: Proxies
- name: ğŸ“º Bilibili
  type: select
  prior: Direct
- name: ğŸ Apple
  type: select
  prior: Direct
- name: ğŸ® Game
  type: select
  prior: Direct
- name: ğŸŒ China
  type: select
  prior: Direct
- name: ğŸ›‘ AdBlock
  type: select
  prior: REJECT
- name: ğŸŸ Final
  type: select
  prior: Proxies
- name: ğŸ‡­ğŸ‡° HongKong
  type: urltest
  rule: false
  regex: ğŸ‡­ğŸ‡°|HK|Hong|Kong|HGC|WTT|CMI|æ¸¯
- name: ğŸ‡¹ğŸ‡¼ TaiWan
  type: urltest
  rule: false
  regex: ğŸ‡¹ğŸ‡¼|TW|Taiwan|æ–°åŒ—|å½°åŒ–|CHT|å°|HINET
- name: ğŸ‡¸ğŸ‡¬ Singapore
  type: urltest
  rule: false
  regex: ğŸ‡¸ğŸ‡¬|SG|Singapore|ç‹®åŸ|^æ–°[^èŠ‚åŒ—]|[^åˆ·æ›´]æ–°[^èŠ‚åŒ—]
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
  type: urltest
  rule: false
  regex: ğŸ‡¯ğŸ‡µ|JP|Japan|Tokyo|Osaka|Saitama|ä¸œäº¬|å¤§é˜ª|åŸ¼ç‰|æ—¥
- name: ğŸ‡ºğŸ‡¸ America
  type: urltest
  rule: false
  regex: ğŸ‡ºğŸ‡¸|US|America|United.*?States|ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥
